### ISSUE TITLE
Problem with module on IOS

### ISSUE THREAD

**Issue by webquali** [igorizr1/wSQL#1]
Hello your module work great. But today I get problem on IOS. When I do insert to table, ten I cannot get insertId, it's empty. But the same functional great working on browser.
Can you help me to understand where problem?

**Comment by igorizr1** [comment]
Hello, I didn't faced this issue before.
Which iOS version are u using and which device?
May u please console.log(results) on the line 95 in /src/wSQL.js and provide logs?

That would be really helpfull.

**Comment by webquali** [comment]
Can you add me to your skype? My skype:wog526
