### ISSUE TITLE
wSQL.select is not a function

### ISSUE THREAD

**Issue by fsebbah** [igorizr1/wSQL#3]
Hi Igor,
I installed wSQL via bower:  bower install angular-wsql
I used the version 1.3.18 of angular, angular-wsql 0.8.5 and 1.5.2 of bower

The file of  configuration : wSQL.config.js
angular.module('wSQL.config',[])
  .constant('W_SQL_CONFIG',{
    PARAMS:{
      name:"../data/Synchronization.db",
      version: "1.0",
      size: 1000000
    },
The file app.js
var myApp=angular.module("myApp",['myApp.services','wSQL']);
The file sqlController.js (I have 2 controllers file)
angular.module('myApp')
.controller('sqlController',function($scope,wSQL){
  wSQL
    .select("*")
    .from("myTable1")
    .row()
    .then(function(d){
      console.log(d);  
    })
})

In the file index.html
The order of the script file
public/lib/angular/angular.js"
public/lib/angular-wsql/src/wSQL.js"
js/app.js"
js/wSQL.config.js"
js/fileController.js"
js/sqlController.js"
js/services.js"
js/script.js"
js/getData.js"
I add :
<html ng-app="myApp">

<div ng-controller="sqlController"></div>

I have an error
TypeError: wSQL.select is not a function
    at new <anonymous> (sql-access.js:4)
    at Object.invoke (angular.js:4219)
    at extend.instance (angular.js:8525)
    at angular.js:7771
    at forEach (angular.js:334)
    at nodeLinkFn (angular.js:7770)
    at compositeLinkFn (angular.js:7149)
    at compositeLinkFn (angular.js:7152)
    at compositeLinkFn (angular.js:7152)
    at publicLinkFn (angular.js:7028)

The 2 files angular.js and wSQL.js are found in debugg console of Chrome.
If you have an idea, 
Thanks,
Franck

**Comment by fsebbah** [comment]
I forgot : 
      sub_name:"my_db_sub_name",

But it's not good for me because, I work with a real SQLite database.

**Comment by igorizr1** [comment]
Sorry, does work not for u when u added sub_name?

2015-08-30 17:52 GMT+03:00 fsebbah notifications@github.com:

**Comment by fsebbah** [comment]
Hi Igor your product is perfect but in fact I work with a real database SQLITE3 vi a client js.
And wSQL dow't work with.
I don't  understand why there are not a plugin to work a real database SQLITE3 ?
Tks for your response.
