### ISSUE TITLE
arguments_max_length too high

### ISSUE THREAD

**Issue by SmailHammour** [igorizr1/wSQL#9]
According to the official SQLITE docs the max size for arguments_max_length should be 500. 

> Maximum Number Of Terms In A Compound SELECT Statement. <br>
> A compound SELECT statement is two or more SELECT statements connected by operators UNION, UNION ALL, EXCEPT, or INTERSECT. We call each individual SELECT statement within a compound SELECT a "term". <br>
> The code generator in SQLite processes compound SELECT statements using a recursive algorithm. In order to limit the size of the stack, we therefore limit the number of terms in a compound SELECT. The maximum number of terms is SQLITE_MAX_COMPOUND_SELECT which defaults to **500**. We think this is a generous allotment since in practice we almost never see the number of terms in a compound select exceed single digits.

Anything above this will result in errors.

PR: https://github.com/igorizr1/wSQL/pull/10

**Comment by igorizr1** [comment]
Thx. Approved and merged your PR
